import 'package:flutter/material.dart';

const Map<String, String> languageNames = {
  'af': 'Afrikaans',
  'sq': 'Shqip',
  'am': 'አማርኛ',
  'ar': 'العربية',
  'hy': 'Արևելահայերեն',
  'hyw': 'Արևմտահայերեն',
  'az': 'Azərbaycan dili',
  'bss': 'Ɓàsàa',
  'be': 'Беларуская',
  'bn': 'বাংলা',
  'bs': 'Bosanski',
  'br': 'Braille',
  'bg': 'Български',
  'my': 'မြန်မာ',
  'km': 'ភាសាខ្មែរ',
  'kri': 'Kriolu',
  'ceb': 'Cebuano',
  'zh-CN': '简体中文',
  'zh-TW': '繁體中文',
  'chk': 'Chuukese',
  'hr': 'Hrvatski',
  'cs': 'Čeština',
  'da': 'Dansk',
  'prs': 'دری',
  'nl': 'Nederlands',
  'en': 'English',
  'et': 'Eesti',
  'fa': 'فارسی',
  'fi': 'Suomi',
  'vls': 'Vlaams',
  'fr-CA': 'Français (Canada)',
  'fr-FR': 'Français (France)',
  'ff': 'Fulfulde',
  'ka': 'ქართული',
  'de': 'Deutsch',
  'el': 'Ελληνικά',
  'gu': 'ગુજરાતી',
  'ht': 'Kreyòl Ayisyen',
  'lus': 'Laiholh',
  'hak': '客家話',
  'he': 'עברית',
  'hi': 'हिन्दी',
  'mww': 'Hmoob',
  'hu': 'Magyar',
  'is': 'Íslenska',
  'ig': 'Igbo',
  'ilo': 'Ilokano',
  'hil': 'Hiligaynon',
  'id': 'Bahasa Indonesia',
  'it': 'Italiano',
  'ja': '日本語',
  'jv': 'Basa Jawa',
  'kn': 'ಕನ್ನಡ',
  'ksw': 'ကညီကျိာ်',
  'kk': 'Қазақша',
  'rw': 'Ikinyarwanda',
  'rn': 'Ikirundi',
  'ko': '한국어',
  'kmr': 'Kurdî (Kurmancî)',
  'ckb': 'کوردی (سۆرانی)',
  'ky': 'Кыргызча',
  'lo': 'ພາສາລາວ',
  'lv': 'Latviešu',
  'lt': 'Lietuvių',
  'mk': 'Македонски',
  'ms': 'Bahasa Melayu',
  'mnk': "Mandi'nka",
  'mr': 'मराठी',
  'mh': 'Kajin M̧ajeļ',
  'mnn': 'Mienh',
  'mn': 'Монгол',
  'cnr': 'Crnogorski',
  'nv': 'Diné Bizaad',
  'ne': 'नेपाली',
  'no': 'Norsk',
  'om': 'Afaan Oromoo',
  'ps': 'پښتو',
  'pl': 'Polski',
  'pt-BR': 'Português (Brasil)',
  'pt-PT': 'Português (Portugal)',
  'pa': 'ਪੰਜਾਬੀ',
  'rhg': '𐴌𐴇𐴂𐴇𐴐𐴝',
  'ro-MD': 'Română (Moldova)',
  'ru': 'Русский',
  'sr': 'Српски',
  'sk': 'Slovenčina',
  'sl': 'Slovenščina',
  'so': 'Soomaali',
  'es-ES': 'Español (Castellano)',
  'es-419': 'Español (Latinoamericano)',
  'es': 'Español (otras variedades)',
  'sw': 'Kiswahili',
  'sv': 'Svenska',
  'tl': 'Tagalog',
  'ta': 'தமிழ்',
  'te': 'తెలుగు',
  'th': 'ไทย',
  'bo': 'བོད་སྐད་',
  'ti': 'ትግርኛ',
  'tr': 'Türkçe',
  'uk': 'Українська',
  'ur': 'اردو',
  'uz': "Oʻzbekcha",
  'vi': 'Tiếng Việt',
  'wo': 'Wolof',
  'yo': 'Yorùbá',
  'zu': 'isiZulu',
  'xh': 'isiXhosa',
  'st': 'Sesotho',
  'tn': 'Setswana',
  'nso': 'Sepedi',
  'ts': 'Xitsonga',
  've': 'Tshivenda',
  'nr': 'isiNdebele',
  'mg': 'Malagasy',
  'mi': 'Te Reo Māori',
  'sm': 'Gagana Samoa',
  'to': 'Lea Faka-Tonga',
  'fj': 'Vakaviti',
  'haw': 'ʻŌlelo Hawaiʻi',
  'cy': 'Cymraeg',
  'ga': 'Gaeilge',
  'gd': 'Gàidhlig',
  'eu': 'Euskara',
  'ca': 'Català',
  'gl': 'Galego',
  'eo': 'Esperanto',
};

const List<String> languageOrder = [
  'af', 'sq', 'am', 'ar', 'hy', 'hyw', 'az', 'bss', 'be', 'bn',
  'bs', 'br', 'bg', 'my', 'km', 'kri', 'ceb', 'zh-CN', 'zh-TW',
  'chk', 'hr', 'cs', 'da', 'prs', 'nl', 'en', 'et', 'fa', 'fi',
  'vls', 'fr-CA', 'fr-FR', 'ff', 'ka', 'de', 'el', 'gu', 'ht',
  'lus', 'hak', 'he', 'hi', 'mww', 'hu', 'is', 'ig', 'ilo', 'hil',
  'id', 'it', 'ja', 'jv', 'kn', 'ksw', 'kk', 'rw', 'rn', 'ko',
  'kmr', 'ckb', 'ky', 'lo', 'lv', 'lt', 'mk', 'ms', 'mnk', 'mr',
  'mh', 'mnn', 'mn', 'cnr', 'nv', 'ne', 'no', 'om', 'ps', 'pl',
  'pt-BR', 'pt-PT', 'pa', 'rhg', 'ro-MD', 'ru', 'sr', 'sk', 'sl',
  'so', 'es-ES', 'es-419', 'es', 'sw', 'sv', 'tl', 'ta', 'te', 'th',
  'bo', 'ti', 'tr', 'uk', 'ur', 'uz', 'vi', 'wo', 'yo',
  'zu', 'xh', 'st', 'tn', 'nso', 'ts', 've', 'nr', 'mg', 'mi',
  'sm', 'to', 'fj', 'haw', 'cy', 'ga', 'gd', 'eu', 'ca', 'gl', 'eo',
];

Locale codeToLocale(String code) {
  if (code.contains('-')) {
    final parts = code.split('-');
    return Locale(parts[0], parts[1]);
  }
  return Locale(code);
}
